### ISSUE TITLE
Resource not found errors

### ISSUE THREAD

**Issue by alashow** [xiprox/ErrorView#11]
Hello,

Have you seen this kind of errors before?
http://crashes.to/s/f59f7ecad55

```ruby
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080078
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:239)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:705)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:585)
       at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:308)
       at android.content.res.Resources.loadDrawable(Resources.java:872)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
       at android.widget.ImageView.(ImageView.java:157)
       at android.widget.ImageView.(ImageView.java:145)
       at androidx.appcompat.widget.AppCompatImageView.(SourceFile:72)
       at androidx.appcompat.widget.AppCompatImageView.(SourceFile:68)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(SourceFile:182)
       at androidx.appcompat.app.AppCompatViewInflater.createView(SourceFile:106)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(SourceFile:1266)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(SourceFile:1316)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
       at tr.xip.errorview.ErrorView.access$getRetryListener$p(SourceFile:74)
       at tr.xip.errorview.ErrorView.(SourceFile:50)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:989)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:879)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1019)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:879)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
       at androidx.databinding.DataBindingUtil.inflate(SourceFile:126)
       at androidx.databinding.DataBindingUtil.inflate(SourceFile:95)
       at my.app.BaseFragment.onCreateView(SourceFile:31)
       at my.app.MyFragment.onCreateView(SourceFile:39)
       at androidx.fragment.app.Fragment.performCreateView(SourceFile:2439)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(SourceFile:1460)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(SourceFile:1852)
       at androidx.fragment.app.BackStackRecord.executeOps(SourceFile:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(SourceFile:2625)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(SourceFile:2273)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(SourceFile:3273)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:3229)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at androidx.fragment.app.FragmentActivity.onStart(SourceFile:620)
       at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
       at android.app.Activity.performStart(Activity.java:6873)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6342)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Comment by alashow** [comment]
More here: http://crashes.to/s/926b0ac4d4a
